version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: lara_nginx
    volumes:
      - ./src:/var/www/aquinotas
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:81"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/aquinotas
    container_name: lara_php
    ports:
      - "9004:9004"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: lara_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel    
